### ISSUE TITLE
.htaccess alternative

### ISSUE THREAD

**Issue by m00racle** [mooracle/trialpos#13]
There are chances that the web app will not be run in Apache web server. I think it will be wiser if the config file is added when the web server used is clear. 
Moreover, the htaccess file used mainly for two things:
1. Indexing option that make the web server prevent file indexing 
2. Rewrite rule for the URL references.
```
Options All -Indexes

RewriteEngine On

RewriteRule ^([-a-zA-Z0-9/]+)$ index.php?route=$1
```
Even as the Options All index is will still useful the RewriteEngine will be wiser if it will be removed. 

The rewrite rule only redirect the URL to index.php?route= which this can be directly put on each href.

**Comment by mooracle** [comment]
This will be a good opportunity to trim and improve the syntax of the whole source code. 

Clean the comments like :
DEBUG: consider to change into TEMP:
then some NOTE: can be improved to WARNIG: for some cases.

**Comment by m00racle** [comment]
Already change some href link and windows location h ref and replaces but have not add them into the local Git. 

**htaccess also has not being commented out!**

test them after changing the .htaccess file and then if all okay just add the changes into git.
